// Generated by CoffeeScript 1.4.0
(function() {

  window.AccountController = function($scope, $http) {
    return $http.get("/api/account.json").success(function(data) {
      $scope.recipes = _.map(data.user.recipes, function(d) {
        return new Recipe(d);
      });
      $scope.user = new User({
        id: data.user.id,
        username: data.user.username,
        image_url: data.user.image_url
      });
      return $scope.cookbooks = data.user.cookbooks;
    });
  };

}).call(this);
