// Generated by CoffeeScript 1.4.0
(function() {

  app.controller('AddRecipeToShoppingListController', function($scope, ShoppingItem, Recipe) {
    this.setRecipe = function(recipe) {
      $scope.recipe = recipe;
      $scope.items = _.map(recipe.ingredients(), function(i) {
        var newIng;
        newIng = _.clone(i);
        newIng.checked = true;
        return newIng;
      });
      return $scope.$digest();
    };
    return $scope.submit = function() {
      var items_to_add;
      items_to_add = _.select($scope.items, function(i) {
        return i.checked;
      });
      return _.each(items_to_add, function(item) {
        var c;
        c = new ShoppingItem({
          name: item.name,
          recipe_id: $scope.recipe.id
        });
        return c.$save();
      });
    };
  });

}).call(this);
