// Generated by CoffeeScript 1.4.0
(function() {

  app.controller('ApplicationController', function($scope, $window, Favorite, User) {
    $scope.favorite = function(recipe) {
      return Favorite.add(recipe);
    };
    $scope.unfavorite = function(recipe) {
      return Favorite.remove(recipe);
    };
    $scope.isFavorite = function(recipe) {
      return Favorite.is(recipe);
    };
    $scope.search = function(q) {
      return $window.location.hash = "#/search?q=" + q;
    };
    return $scope.user = function() {
      return User.current();
    };
  });

}).call(this);
