// Generated by CoffeeScript 1.4.0
(function() {

  window.ApplicationController = function($scope, Favorite) {
    $scope.favorite = function(recipe) {
      return Favorite.add(recipe);
    };
    $scope.unfavorite = function(recipe) {
      return Favorite.remove(recipe);
    };
    return $scope.isFavorite = function(recipe) {
      return Favorite.is(recipe);
    };
  };

}).call(this);
