// Generated by CoffeeScript 1.4.0
(function() {

  window.ApplicationController = function($scope, $window, Favorite) {
    $scope.favorite = function(recipe) {
      return Favorite.add(recipe);
    };
    $scope.unfavorite = function(recipe) {
      return Favorite.remove(recipe);
    };
    $scope.isFavorite = function(recipe) {
      return Favorite.is(recipe);
    };
    return $scope.search = function(q) {
      return $window.location.hash = "#/search?q=" + q;
    };
  };

}).call(this);
