// Generated by CoffeeScript 1.4.0
(function() {

  app.controller('FavoritesController', function($scope, $http, Favorite) {
    return $scope.recipes = function() {
      return Favorite.recipes();
    };
  });

}).call(this);
