// Generated by CoffeeScript 1.4.0
(function() {

  window.FavoritesController = function($scope, $http, Favorite) {
    return $scope.recipes = function() {
      return Favorite.recipes();
    };
  };

}).call(this);
