// Generated by CoffeeScript 1.4.0
(function() {

  app.controller('SearchController', function($scope, $routeParams, $http, Recipe) {
    var update;
    update = function() {
      $scope.query = $routeParams.q;
      return $http.get("/api/search?q=" + $scope.query).success(function(res) {
        $scope.recipes = _.map(res.recipes, function(r) {
          return new Recipe(r);
        });
        return $scope.total = res.total_entries;
      });
    };
    $scope.$on('$routeUpdate', update);
    return update();
  });

}).call(this);
