// Generated by CoffeeScript 1.4.0
(function() {

  window.ShoppingListController = function($scope, $http, ShoppingItem) {
    ShoppingItem.query(function(data) {
      return $scope.items = data;
    });
    $scope.create = function(name) {
      var c;
      if (!name.match(/[^ ]+/)) {
        return;
      }
      c = new ShoppingItem({
        name: name
      });
      c.$save();
      $scope.items.push(c);
      return $scope.newItemName = '';
    };
    $scope.removeAll = function() {
      return console.log("remove all");
    };
    return $scope.removeSelected = function() {
      var res;
      res = _.groupBy($scope.items, function(i) {
        return !!i.checked;
      });
      $scope.items = res["false"];
      return _.each(res["true"], function(i) {
        return i.$delete({
          id: i.id
        });
      });
    };
  };

}).call(this);
