// Generated by CoffeeScript 1.4.0
(function() {

  app.directive('authorized', function(User) {
    return {
      link: function(scope, element) {
        return $(element).click(function(evt) {
          var el;
          if (!User.current()) {
            el = angular.element('.authorization-modal');
            el.reveal();
            return evt.stopImmediatePropagation();
          }
        });
      }
    };
  });

}).call(this);
