// Generated by CoffeeScript 1.4.0
(function() {

  app.directive('closeRevealModal', function() {
    return {
      link: function(scope, element, attrs, ctrl) {
        return $(element).click(function() {
          return element.closest('.reveal-modal').trigger('reveal:close');
        });
      }
    };
  });

}).call(this);
