// Generated by CoffeeScript 1.4.0
(function() {

  app.directive('revealAddRecipeToShoppingList', function() {
    return {
      scope: {
        recipeToAdd: "=recipe"
      },
      link: function(scope, element, attrs, ctrl) {
        return $(element).click(function() {
          var el;
          el = angular.element('.shopping-list-modal');
          el.controller().setRecipe(scope.recipeToAdd);
          return el.reveal();
        });
      }
    };
  });

}).call(this);
