// Generated by CoffeeScript 1.4.0
(function() {

  app.filter('squish', function() {
    return function(stringInput) {
      return stringInput.replace(/^\s\s*/, '').replace(/\s\s*$/, '');
    };
  });

}).call(this);
