// Generated by CoffeeScript 1.4.0
(function() {

  window.Cookbook = (function() {

    function Cookbook(attributes) {
      _.extend(this, attributes);
    }

    return Cookbook;

  })();

}).call(this);
