// Generated by CoffeeScript 1.4.0
(function() {

  app.factory('Favorite', function($resource, $http, $q, Recipe) {
    var data, resource;
    data = {
      favorites: [],
      recipes: []
    };
    resource = $resource('/api/bookmarks/:id', {});
    $http.get("/api/bookmarks.json").success(function(res) {
      data.favorites = res.bookmarks;
      return data.recipes = _.map(res.recipes, function(r) {
        return new Recipe(r);
      });
    });
    return {
      recipes: function() {
        return data.recipes;
      },
      is: function(recipe) {
        if (!recipe) {
          return false;
        }
        return _.find(data.favorites, function(f) {
          return f.recipe_id === recipe.id;
        });
      },
      remove: function(recipe) {
        var f;
        f = _.find(data.favorites, function(f) {
          return f.recipe_id === recipe.id;
        });
        data.favorites = _.without(data.favorites, f);
        return (new resource).$delete({
          id: f.id
        });
      },
      add: function(recipe) {
        var f;
        f = new resource({
          recipe_id: recipe.id
        });
        f.$save();
        return data.favorites.push(f);
      }
    };
  });

}).call(this);
