// Generated by CoffeeScript 1.4.0
(function() {

  app.factory('Recipe', function($resource) {
    var res;
    res = $resource('/api/recipes/:id', {}, {
      index: {
        method: 'GET',
        isArray: true
      }
    });
    _.extend(res.prototype, {
      app_url: function() {
        return "#/recipes/" + this.id + "-" + (this.title.replace(/[^A-Za-z0-9]/g, '-').toLowerCase());
      },
      thumb_url: function() {
        var _ref, _ref1;
        return ((_ref = this.uploads) != null ? (_ref1 = _ref[0]) != null ? _ref1.thumb_url : void 0 : void 0) || "http://www.littlechefapp.com/assets/recipe_photo_placeholder.gif";
      },
      ingredients: function() {
        return _.flatten(_.pluck(this.sections, 'ingredient_sections'));
      }
    });
    return res;
  });

}).call(this);
