// Generated by CoffeeScript 1.4.0
(function() {

  app.factory('ShoppingItem', function($resource) {
    return $resource('/api/shopping_items/:id', {
      id: '@id'
    }, {
      index: {
        method: 'GET',
        isArray: true
      },
      update: {
        method: 'PUT'
      }
    });
  });

}).call(this);
