// Generated by CoffeeScript 1.4.0
(function() {

  app.factory('User', function($http) {
    var data;
    data = {
      current: null
    };
    $http.get('/api/account.json').success(function(res) {
      return data.current = res.user;
    });
    return {
      current: function() {
        return data.current;
      }
    };
  });

}).call(this);
